version: "3"
services:
  ml-server:
    build: ./ml-server
    image:  markpotanin/ml-server
    container_name: ml-server
    ports:
      - 8001:8001
  ml-client:
    build: ./ml-client
    image: markpotanin/ml-client
    container_name: ml-client
    ports:
      - 3000:3000
    depends_on:
      - ml-server
  #nginx:
  #  image: nginx
  #  build: ./nginx
  #  container_name: nginx
  #  ports:
  #    - 80:80
  #  depends_on:
  #    - ml-client